// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_fJAeGZZYsysCHCTjRWiIlbwZodtVwUc',
    appId: '1:581916365752:web:394cdedcb55b6f83eb754d',
    messagingSenderId: '581916365752',
    projectId: 'lab3-c2480',
    authDomain: 'lab3-c2480.firebaseapp.com',
    storageBucket: 'lab3-c2480.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHkrhwylfioUxLesEiTaUcd5s9PqCfDfE',
    appId: '1:581916365752:android:6afd8c509febe37aeb754d',
    messagingSenderId: '581916365752',
    projectId: 'lab3-c2480',
    storageBucket: 'lab3-c2480.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmERpaRTEV9drhMh-Kuk5HwkIktBue5HQ',
    appId: '1:581916365752:ios:31113d62d9bd2b98eb754d',
    messagingSenderId: '581916365752',
    projectId: 'lab3-c2480',
    storageBucket: 'lab3-c2480.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmERpaRTEV9drhMh-Kuk5HwkIktBue5HQ',
    appId: '1:581916365752:ios:31113d62d9bd2b98eb754d',
    messagingSenderId: '581916365752',
    projectId: 'lab3-c2480',
    storageBucket: 'lab3-c2480.firebasestorage.app',
    iosBundleId: 'com.example.lab3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_fJAeGZZYsysCHCTjRWiIlbwZodtVwUc',
    appId: '1:581916365752:web:617fde0da1bfb43aeb754d',
    messagingSenderId: '581916365752',
    projectId: 'lab3-c2480',
    authDomain: 'lab3-c2480.firebaseapp.com',
    storageBucket: 'lab3-c2480.firebasestorage.app',
  );
}
